### PR TITLE
Bugfix/incompatibility with setuptools 63.4.0

### PR DESCRIPTION
**Pull request by StefanD986**
setuptools removed the `format_command` property of the `bdist` command, which setuptools-cythonize relies on.

This results in the following error:
```
File "D:\win_temp\pip-build-env-avucl34u\overlay\Lib\site-packages\setuptools_cythonize.py", line 166, in set_default_wheel_format
    cls.format_command['wheel'] = ('bdist_wheel', "Python .whl file")
AttributeError: type object 'CythonizeBdist' has no attribute 'format_command'
```

This PR contains two solutions:
- It still works with setuptools versions <=63.3.0, so a workaround is to constrain the setuptools version to that (commit 318c6b4d13961409472485febeaa0ca47636f27d)
- A future proof, way is in the second commit (aadd7667c7fc103b7e13ad4a0154f990fbcecd41), where only the `format_commands` `dict` (note the `s` at the end) is used, because since 63.3.0 this `dict` will retain the order, the list is not required/supported anymore. Because this is a fix that is not compatible with setuptools <63.3.0 the constraint in the `setup.py` was updated.

@anxuae I would suggest to make separate releases for the two commits, so that people who cannot use setuptools 63.4.0 for any reason can still fall back to the backwards compatible first fix.

### CODE REVIEW

**Comment by jaraco** [comment]
I was not aware this interface was used publicly. I'll restore the compatibility shim.

I'd recommend setuptools-cythonize to implement something like pypa/setuptools@b8d50cf4f7431ed617957e7d6e432a1729656524 for backward compatibility if it's unacceptable to drop support for older Setuptools.

**Comment by jaraco** [comment]
Setuptools v63.4.1 is going out and should address the incompatibility. I'd still like to see setuptools-cythonize adapt to the new preferred interface.

**Comment by anxuae** [comment]
Thanks for reporting @StefanD986!

As @jaraco suggest it, I will implement a way to address the incompatibility

**Comment by anxuae** [comment]
Hi @StefanD986,

Can you try if the changes I've made fit for your needs?

**Comment by StefanD986** [comment]
I tested it with setuptools 63.4.0 and 63.4.1 (these were the problematic versions for me), and the changes solve it for these. Thanks!

Sidenote: Trying this out is in theory easy (just specify the wheel as a direct reference) but was surprisingly hard: I was running into a [bug in the `packaging` package](https://github.com/pypa/packaging/issues/120) that seems to have problems when a package was installed from a `file:///` URL. In the end I worked around it by creating an sdist and deploying it to an internal pypi mirror.
